branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode7.3
script:
  - xctool -project UIViewNibExtensionsExample.xcodeproj -sdk iphonesimulator -scheme UIViewNibExtensionsExample
  - xctool -project UIViewNibExtensionsExample.xcodeproj -sdk iphonesimulator -scheme UIViewNibExtensionsExample test